openapi: "3.0.3"

info:
  title: "サンプルのAPI"
  version: "1.0.0"

paths:
  "/message":
    get:
      summary: "GET APIのサンプル"
      description: "GET APIのサンプル"
      responses:
        "200":
          description: "成功"
          content:
            application/json:
              schema:
                type: string
                format: byte
                example: "Hello World!!"
        "201":
          description: "成功"
          content:
            application/json:
              schema:
                type: string
                example: ""